-- Create notification preferences table for storing user notification settings
create table public.notification_preferences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  member_id bigint references public.members(id) on delete cascade not null unique,
  push_enabled boolean not null default true,
  email_enabled boolean not null default true,
  in_app_enabled boolean not null default true,
  announcement_notifications boolean not null default true,
  event_notifications boolean not null default true,
  points_notifications boolean not null default true,
  system_notifications boolean not null default true
);

-- Enable Row Level Security
alter table public.notification_preferences enable row level security;

-- RLS Policies
create policy "Allow members to manage their own notification preferences" on public.notification_preferences
  for all to authenticated
  using (
    exists (
      select 1 from members
      where members.id = member_id
      and members.user_id = auth.uid()
    )
  );

create policy "Allow organizers to view all notification preferences" on public.notification_preferences
  for select to authenticated
  using (
    exists (
      select 1 from members
      where members.user_id = auth.uid()
      and (members.title = 'Organiser' or members.title = 'Admin')
    )
  );

-- Create index for faster lookups
create index on public.notification_preferences (member_id);
