-- Create push subscriptions table for storing Web Push API subscriptions
create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  endpoint text not null unique,
  p256dh text not null, -- Public key for encryption
  auth text not null, -- Auth secret for encryption
  member_id bigint references public.members(id) on delete cascade not null
);

-- Enable Row Level Security
alter table public.push_subscriptions enable row level security;

-- RLS Policies
create policy "Allow members to manage their own push subscriptions" on public.push_subscriptions
  for all to authenticated
  using (
    exists (
      select 1 from members
      where members.id = member_id
      and members.user_id = auth.uid()
    )
  );

create policy "Allow organizers to view all push subscriptions" on public.push_subscriptions
  for select to authenticated
  using (
    exists (
      select 1 from members
      where members.user_id = auth.uid()
      and (members.title = 'Organiser' or members.title = 'Admin')
    )
  );

-- Create index for faster lookups
create index on public.push_subscriptions (member_id);
create index on public.push_subscriptions (endpoint);
