-- Create the members table
create table public.members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  points integer default 0 not null,
  avatar_url text
);

-- Enable Row Level Security
alter table public.members enable row level security;

-- Create a policy that allows all operations
create policy "Allow all operations" on public.members
  for all
  using (true)
  with check (true);

-- Create an index on points for faster leaderboard queries
create index members_points_idx on public.members (points desc);

